# Generated by Django 3.1.6 on 2021-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('mname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=15)),
                ('contact', models.BigIntegerField(max_length=10)),
                ('password', models.IntegerField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.BigIntegerField(max_length=12)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
