# Generated by Django 3.1.6 on 2021-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.IntegerField(),
        ),
    ]
