# Generated by Django 3.1.6 on 2021-03-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210304_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mname',
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
